customhost = "homelab-db.caqtuvix9696.sa-east-1.rds.amazonaws.com"
customuser = "username"
custompass = "password"
customdb = "employee"
custombucket = "homelab-project-s3-bucket"
customregion = "sa-east-1"
customtable = "employee_image_table"
